---
abstract: 'An extended version of the canvas widget for plotting 2D line graphs. Plots have a legend and zooming capabilities.'
author:
  - 'I.T. Dev Ltd.'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Pod::Coverage: 0.18
  Test::More: 0
  Test::Pod: 1.22
  Test::Pod::Coverage: 1.08
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tk-PlotDataset
no_index:
  directory:
    - inc
    - t
recommends:
  Tk::LineGraphDataset: 0
requires:
  Carp: 0
  POSIX: 0
  Tk::Balloon: 0
  Tk::Canvas: 0
  perl: 5.00503
resources:
  license: http://dev.perl.org/licenses/
version: 2.03
